(function(){
  async function boot(){
    // Settings button
    document.getElementById('btn-settings').addEventListener('click', ()=>{
      TrackboardRouter.go('settings');
    });
    // Register service worker for offline
    if('serviceWorker' in navigator){
      window.addEventListener('load', ()=>{
        navigator.serviceWorker.register('sw.js').then((reg)=>{
          // If a new SW is installed while this page is controlled, tell the user to refresh.
          reg.addEventListener('updatefound', ()=>{
            const newWorker = reg.installing;
            if(!newWorker) return;
            newWorker.addEventListener('statechange', ()=>{
              if(newWorker.state === 'installed' && navigator.serviceWorker.controller){
                if(window.TrackboardUI && TrackboardUI.toast){
                  TrackboardUI.toast('Update available. Refresh to apply.');
                }
              }
            });
          });
        }).catch(()=>{});
      });
    }


    // Init security + theme before first render
    if(window.Security && Security.init){
      await Security.init();
    }

// --- Companion first-launch intro (Sprint 4) ---
async function showCompanionIntro(){
  // If locked, don't show intro now.
  if(window.Security && Security.isEnabled && Security.isEnabled() && Security.isUnlocked && !Security.isUnlocked()){
    return;
  }
  const seen = await Store.getSetting('companion_intro_seen');
  if(seen) return;

  const makeModal = ()=> UI && UI.h ? UI.h : null;
  if(!window.UI || !UI.h){
    // Fallback: mark as seen to avoid repeated prompts if UI isn't ready.
    await Store.setSetting('companion_intro_seen', true);
    return;
  }

  function openConsent(){
    return new Promise((resolve)=>{
      const modal = UI.h('div',{class:'modal open', id:'modal-online-ai', role:'dialog','aria-modal':'true'},[]);
      const card = UI.h('div',{class:'modal-card'},[]);
      const head = UI.h('div',{class:'modal-head'},[
        UI.h('div',{class:'h2'},['Enable Online AI?']),
        UI.h('button',{class:'icon-btn', type:'button', 'aria-label':'Close', title:'Close', onClick:async ()=>{
          modal.remove(); resolve(false);
        }},['✕'])
      ]);
      const body = UI.h('div',{class:'stack'},[
        UI.h('div',{class:'p'},['If you enable Online AI, some Companion messages may be generated by an online AI service. This can improve reflections, but it means the text you type may be sent over the internet.']),
        UI.h('div',{class:'small muted'},['What is sent: the text you enter in Companion + selected voice.']),
        UI.h('div',{class:'small muted'},['What is not sent: your history (unless you paste it), your passphrase/lock data, or anything from other screens.']),
        UI.h('div',{class:'small muted'},['You can disable Online AI anytime in Settings.'])
      ]);
      const actions = UI.h('div',{class:'row', style:'justify-content:flex-end;gap:10px;margin-top:10px'},[
        UI.h('button',{class:'btn ghost', type:'button', onClick:()=>{ modal.remove(); resolve(false); }},['Cancel']),
        UI.h('button',{class:'btn primary', type:'button', onClick:()=>{ modal.remove(); resolve(true); }},['I agree — Enable Online AI'])
      ]);
      card.appendChild(head);
      card.appendChild(body);
      card.appendChild(actions);
      modal.appendChild(card);
      modal.addEventListener('click',(e)=>{ if(e.target===modal){ modal.remove(); resolve(false); }});
      document.body.appendChild(modal);
    });
  }

  const modal = UI.h('div',{class:'modal open', id:'modal-companion-intro', role:'dialog','aria-modal':'true'},[]);
  const card = UI.h('div',{class:'modal-card'},[]);
  const head = UI.h('div',{class:'modal-head'},[
    UI.h('div',{class:'h2'},['Meet Companion']),
    UI.h('button',{class:'icon-btn', type:'button', 'aria-label':'Close', title:'Close', onClick:async ()=>{
      // Treat close as "Not now"
      await Store.setSetting('companion_enabled', false);
      await Store.setSetting('online_ai_enabled', false);
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
    }},['✕'])
  ]);

  const body = UI.h('div',{class:'stack'},[
    UI.h('div',{class:'p'},['Companion helps you notice patterns, reflect on moods, and gently support your goals — from daily check-ins to alcohol tracking and stress.']),
    UI.h('div',{class:'p'},['It’s optional. You stay in control.']),
    UI.h('div',{class:'small muted'},['Companion can work offline using on-device templates, or online using AI to generate deeper reflections. You choose how far it goes.']),
    UI.h('details',{},[
      UI.h('summary',{class:'small', style:'cursor:pointer'},['What does Companion do?']),
      UI.h('div',{class:'small muted', style:'margin-top:6px'},['Short replies in one of three voices: Gentle, Supportive, Direct. No judgement. No hype. Just a small nudge when you want it.'])
    ])
  ]);

  const actions = UI.h('div',{class:'stack'},[
    UI.h('button',{class:'btn full', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', true);
      await Store.setSetting('online_ai_enabled', false);
      await Store.setSetting('companion_voice', (await Store.getSetting('companion_voice')) || 'gentle');
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
      // Initialize UI if available
      if(window.TrackboardUI && TrackboardUI.initCompanion) TrackboardUI.initCompanion();
    }},['Use Companion (offline only)']),
    UI.h('button',{class:'btn full primary', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', true);
      await Store.setSetting('companion_voice', (await Store.getSetting('companion_voice')) || 'gentle');
      const ok = await openConsent();
      await Store.setSetting('online_ai_enabled', !!ok);
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
      if(window.TrackboardUI && TrackboardUI.initCompanion) TrackboardUI.initCompanion();
    }},['Use Companion with Online AI']),
    UI.h('button',{class:'btn full ghost', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', false);
      await Store.setSetting('online_ai_enabled', false);
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
    }},['Not now']),
    UI.h('div',{class:'small muted', style:'text-align:center'},['You can change this anytime in Settings.'])
  ]);

  card.appendChild(head);
  card.appendChild(body);
  card.appendChild(actions);
  modal.appendChild(card);
  modal.addEventListener('click',(e)=>{ if(e.target===modal){ /* don't auto-close */ }});
  document.body.appendChild(modal);
}

    // Active date picker (Phase A)
    // The subtitle renders a date button with a calendar icon; we also allow clicking
    // empty subtitle space to open the date picker (helpful on mobile).
    const sub = document.getElementById('brand-subtitle');
    if(sub){
      sub.title = 'Choose a day';
      sub.addEventListener('click', (e)=>{
        const cur = TrackboardRouter.current && TrackboardRouter.current();
        if(cur === 'unlock') return;
        // If a real button was clicked (date button / go-to-today), let it handle.
        if(e.target && e.target.closest && e.target.closest('button')) return;
        if(window.TrackboardUI && TrackboardUI.openDatePicker){
          TrackboardUI.openDatePicker();
        }
      });
    }

    // Re-render current screen when active date changes
    window.addEventListener('tb:activeDate', ()=>{
      const cur = TrackboardRouter.current && TrackboardRouter.current();
      if(cur && cur !== 'unlock') TrackboardRouter.go(cur);
    });
    await showCompanionIntro();
    TrackboardRouter.start();

    // Initialize Companion shell (Phase C - Sprint 3 Step 1)
    if(window.TrackboardUI && TrackboardUI.initCompanion) TrackboardUI.initCompanion();

    // If locked, go to unlock
    if(window.Security && Security.isEnabled() && !Security.isUnlocked()){
      TrackboardRouter.go('unlock');
    }
  }

  window.addEventListener('DOMContentLoaded', boot);
})();
