(function(){
  async function boot(){
    // Settings button
    document.getElementById('btn-settings').addEventListener('click', ()=>{
      TrackboardRouter.go('settings');
    });
    // Register service worker for offline
    if('serviceWorker' in navigator){
      window.addEventListener('load', ()=>{
        navigator.serviceWorker.register('sw.js').then((reg)=>{
          // If a new SW is installed while this page is controlled, tell the user to refresh.
          reg.addEventListener('updatefound', ()=>{
            const newWorker = reg.installing;
            if(!newWorker) return;
            newWorker.addEventListener('statechange', ()=>{
              if(newWorker.state === 'installed' && navigator.serviceWorker.controller){
                if(window.TrackboardUI && TrackboardUI.toast){
                  TrackboardUI.toast('Update available. Refresh to apply.');
                }
              }
            });
          });
        }).catch(()=>{});
      });
    }


    // Init security + theme before first render
    if(window.Security && Security.init){
      await Security.init();
    }

// --- Companion first-launch intro (Sprint 4) ---
async function showCompanionIntro(){
  // If locked, don't show intro now.
  if(window.Security && Security.isEnabled && Security.isEnabled() && Security.isUnlocked && !Security.isUnlocked()){
    return;
  }
  const seen = await Store.getSetting('companion_intro_seen');
  if(seen) return;

  // Helper to build DOM nodes safely (no template-tag confusion)
  function el(tag, attrs={}, children=[]){
    const node = document.createElement(tag);
    for(const [k,v] of Object.entries(attrs||{})){
      if(k === 'class') node.className = v;
      else if(k === 'text') node.textContent = v;
      else if(k === 'html') node.innerHTML = v;
      else if(k.startsWith('on') && typeof v === 'function'){
        const evt = k.slice(2).toLowerCase();
        node.addEventListener(evt, v);
      } else {
        node.setAttribute(k, String(v));
      }
    }
    for(const c of (children||[])){
      if(c == null) continue;
      node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
    }
    return node;
  }

  function openConsent(){
    return new Promise((resolve)=>{
      const modal = el('div',{class:'modal open', id:'modal-online-ai', role:'dialog','aria-modal':'true'},[]);
      const card = el('div',{class:'modal-card'},[]);
      const head = el('div',{class:'modal-head'},[
        el('div',{class:'h2', text:'Enable Online AI?'}),
        el('button',{class:'icon-btn', type:'button', 'aria-label':'Close', title:'Close', onClick:()=>{
          modal.remove(); resolve(false);
        }},['✕'])
      ]);

      const body = el('div',{class:'stack'},[
        el('div',{class:'p', text:'If you enable Online AI, some Companion messages may be generated by an online AI service. This can improve reflections and enable future features, but it means the text you type may be sent over the internet.'}),
        el('div',{class:'p', html:'<strong>What is sent:</strong><br>• Text you enter in the Companion panel<br>• Selected voice (Gentle / Supportive / Direct)'}),
        el('div',{class:'p', html:'<strong>What is not sent:</strong><br>• Your history (unless you paste it)<br>• Passphrase / lock data<br>• Other screens’ data'})
      ]);

      const actions = el('div',{class:'row'},[
        el('button',{class:'btn ghost', type:'button', onClick:()=>{ modal.remove(); resolve(false); }},['Cancel']),
        el('button',{class:'btn primary', type:'button', onClick:()=>{ modal.remove(); resolve(true); }},['I agree — Enable Online AI'])
      ]);

      card.appendChild(head);
      card.appendChild(body);
      card.appendChild(actions);
      modal.appendChild(card);
      document.body.appendChild(modal);
    });
  }

  const modal = el('div',{class:'modal open', id:'modal-companion-intro', role:'dialog','aria-modal':'true'},[]);
  const card = el('div',{class:'modal-card'},[]);
  const head = el('div',{class:'modal-head'},[
    el('div',{class:'h2', text:'Meet Companion'}),
    el('button',{class:'icon-btn', type:'button', 'aria-label':'Close', title:'Close', onClick:async ()=>{
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
    }},['✕'])
  ]);

  const body = el('div',{class:'stack'},[
    el('div',{class:'p', text:'Companion helps you notice patterns, reflect on moods, and gently support your goals — from daily check-ins to alcohol tracking and stress.'}),
    el('div',{class:'p', text:'It’s optional. You stay in control.'}),
    el('div',{class:'p', text:'Companion can work offline using on-device templates, or online using AI to generate deeper reflections. You choose how far it goes.'})
  ]);

  const actions = el('div',{class:'stack'},[
    el('button',{class:'btn full', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', true);
      await Store.setSetting('online_ai_enabled', false);
      await Store.setSetting('companion_voice', (await Store.getSetting('companion_voice')) || 'gentle');
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
      if(window.TrackboardUI && TrackboardUI.syncCompanionFromSettings) TrackboardUI.syncCompanionFromSettings();
    }},['Use Companion (offline only)']),

    el('button',{class:'btn full primary', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', true);
      await Store.setSetting('companion_voice', (await Store.getSetting('companion_voice')) || 'gentle');
      const ok = await openConsent();
      await Store.setSetting('online_ai_enabled', !!ok);
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
      if(window.TrackboardUI && TrackboardUI.syncCompanionFromSettings) TrackboardUI.syncCompanionFromSettings();
    }},['Use Companion with Online AI']),

    el('button',{class:'btn full ghost', type:'button', onClick:async ()=>{
      await Store.setSetting('companion_enabled', false);
      await Store.setSetting('online_ai_enabled', false);
      await Store.setSetting('companion_intro_seen', true);
      modal.remove();
      if(window.TrackboardUI && TrackboardUI.syncCompanionFromSettings) TrackboardUI.syncCompanionFromSettings();
    }},['Not now']),

    el('button',{class:'link', type:'button', onClick:()=>{
      const existing = card.querySelector('.details');
      if(existing){ existing.remove(); return; }
      const details = el('div',{class:'p details', text:'Short replies in one of three voices: Gentle, Supportive, Direct. No judgement. No hype. Just a small nudge when you want it.'});
      card.appendChild(details);
    }},['What does Companion do?'])
  ]);

  card.appendChild(head);
  card.appendChild(body);
  card.appendChild(actions);
  modal.appendChild(card);
  document.body.appendChild(modal);
}


    // Active date picker (Phase A)
    // The subtitle renders a date button with a calendar icon; we also allow clicking
    // empty subtitle space to open the date picker (helpful on mobile).
    const sub = document.getElementById('brand-subtitle');
    if(sub){
      sub.title = 'Choose a day';
      sub.addEventListener('click', (e)=>{
        const cur = TrackboardRouter.current && TrackboardRouter.current();
        if(cur === 'unlock') return;
        // If a real button was clicked (date button / go-to-today), let it handle.
        if(e.target && e.target.closest && e.target.closest('button')) return;
        if(window.TrackboardUI && TrackboardUI.openDatePicker){
          TrackboardUI.openDatePicker();
        }
      });
    }

    // Re-render current screen when active date changes
    window.addEventListener('tb:activeDate', ()=>{
      const cur = TrackboardRouter.current && TrackboardRouter.current();
      if(cur && cur !== 'unlock') TrackboardRouter.go(cur);
    });
    await showCompanionIntro();
    TrackboardRouter.start();    // Initialize Companion shell
    if(window.TrackboardUI){
      if(TrackboardUI.syncCompanionFromSettings) await TrackboardUI.syncCompanionFromSettings();
      else if(TrackboardUI.initCompanion) TrackboardUI.initCompanion();

      // Sprint 9: To‑Do is local-only and always available
      if(TrackboardUI.initTodo) TrackboardUI.initTodo();
      if(TrackboardUI.syncTodoIndicator) TrackboardUI.syncTodoIndicator();
    }

    // If locked, go to unlock
    if(window.Security && Security.isEnabled() && !Security.isUnlocked()){
      TrackboardRouter.go('unlock');
    }
  }

  window.addEventListener('DOMContentLoaded', boot);
})();
